# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35def4a1a9deac421b373daa8aef40fac0f6db1ab18b856227b8747794adfc2c5f45ef37056e04fdc43140a593d9440dd4a26617c6eba5521c83c60c9356fd47

test:
  secret_key_base: b85e8befde3257923c96f1abc8cadcbd1ad634725156d34e3fa28f0673ad5568f7ea1a4bd60bf44f4283f4be812932ca9f05f82f5442609f5aa91429f12ec3f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
